### ISSUE TITLE
Add Nav Section to reflect three logo, and menu links - events,  seats and organizers

### ISSUE THREAD

**Issue by geekelo** [geekelo/passlink-events-frontend#3]
**Description:**
Enhance the navigation section of the PassLink application to improve user accessibility and navigation. The updated navigation bar should include a logo and menu links to key sections: Events, Seats, and Organizers.

**Requirements:**
1. **Logo Section:**
   - Add a logo section in the navigation bar.
   - Ensure the logo is appropriately styled and aligned.

2. **Menu Links:**
   - Add new menu links to the navigation bar: Events, Seats, and Organizers.
   - Each link should direct the user to the respective page when clicked.
   - Ensure the links are responsive and properly styled for both desktop and mobile views.

3. **Responsive Design:**
   - Ensure the navigation bar is fully responsive and maintains usability and aesthetic quality across various screen sizes and devices.
   - Test the navigation bar on different devices to confirm the links and logos are correctly displayed and functional.

### Steps to Implement:

1. **Update NavSection Component:**
   - Modify the `NavSection` component to include the logo section and the new menu links.

2. **CSS Updates:**
   - Update the relevant CSS files to style the logo and menu links appropriately.
   - Ensure the styling is responsive and works well on different screen sizes.

3. **Test Navigation:**
   - Test the updated navigation bar on various devices to ensure the logo and links are correctly displayed and functional.
   - Verify the navigation links correctly route to the respective pages.

### Example Code:

**NavSection Component:**
```jsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import '../stylesheets/desktop/navsection.css';
import '../stylesheets/mobile-tablets/navsectionMobile.css';
import logo from '../../assets/passlink.png';

function NavSection() {
  return (
    <div className="navsection">
      {/* Logo Section */}
      <NavLink to="/" className="logoSection">
        <img className="logo" src={logo} alt="logo" />
      </NavLink>
      
      {/* Menu Section */}
      <div className="menuSection">
        <section className="menuItemsSection">
          <NavLink to="/events" className="menuLinks">
            <span className="menuLinkText">Events</span>
          </NavLink>
          <NavLink to="/seats" className="menuLinks">
            <span className="menuLinkText">Seats</span>
          </NavLink>
          <NavLink to="/organizers" className="menuLinks">
            <span className="menuLinkText">Organizers</span>
          </NavLink>
        </section>
      </div>
    </div>
  );
}

export default NavSection;
```

**CSS Updates (navsection.css):**
```css
.navsection {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 20px;
  background-color: #fff;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.logoSection {
  display: flex;
  align-items: center;
}

.logo {
  height: 50px;
}

.menuSection {
  display: flex;
  align-items: center;
}

.menuItemsSection {
  display: flex;
  align-items: center;
}

.menuLinks {
  margin: 0 15px;
  text-decoration: none;
  color: #000;
  font-weight: 500;
}

.menuLinkText {
  font-size: 18px;
}

@media (max-width: 768px) {
  .menuLinks {
    margin: 0 10px;
  }
  
  .menuLinkText {
    font-size: 16px;
  }
}
```

By following this issue description and implementation steps, the navigation bar of the PassLink application will be updated to include a logo and new menu links for Events, Seats, and Organizers, enhancing the overall user experience and navigation.
